apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gestalt-core
  namespace: gestalt-core
spec:
  podSelector:
    matchLabels:
      app: gestalt-core
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 8080
  egress:
    - {}
